run:
  tests: true
  timeout: 5m
  skip-files:
    - ".*\\.pb\\.go"
  skip-dirs-use-default: true

linters-settings:
  goimports:
    local-prefixes: github.com/antoninbas/p4runtime-go-client/

linters:
  disable-all: true
  enable: # see https://golangci-lint.run/usage/linters/
    - unused
    - staticcheck
    - govet
    - gofmt
    - goimports
    - gosec
    - misspell
