name: Go
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - name: Set up Go 1.18
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Check-out code
      uses: actions/checkout@v3
    - name: Build binaries
      run: |
        make
    - name: Run unit tests
      run: |
        make check

  tidy:
    runs-on: [ubuntu-latest]
    steps:
    - name: Set up Go 1.18
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Check-out code
      uses: actions/checkout@v3
    - name: Check tidiness
      run: |
        ./ci/check-tidy.sh

  golangci:
    name: lint
    runs-on: [ubuntu-latest]
    steps:
    - name: Set up Go 1.18
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Check-out code
      uses: actions/checkout@v3
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        # Required: the version of golangci-lint is required and must be specified without patch version:
        # we always use the latest patch version. Keep this version the same with the one in the Makefile!!
        version: v1.45

        # Optional: show only new issues if it's a pull request. The default value is `false`.
        only-new-issues: false
