name: Go
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
    - name: Check-out code
      uses: actions/checkout@v2
    - name: Build binaries
      run: |
        make
    - name: Run unit tests
      run: |
        make check

  tidy:
    runs-on: [ubuntu-latest]
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
    - name: Check-out code
      uses: actions/checkout@v2
    - name: Check tidiness
      run: |
        ./ci/check-tidy.sh
